{"totalCount":42,"grade":"E","repositories":[{"url":"https://github.com/incubateur-ademe/quefairedemesobjets","vulnerabilityAlerts":{"totalCount":42,"nodes":[{"dismissedAt":null,"createdAt":"2024-08-22T13:09:02Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"werkzeug"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-hrfv-mqp8-q5rw"},{"type":"CVE","value":"CVE-2023-46136"}],"references":[{"url":"https://github.com/pallets/werkzeug/security/advisories/GHSA-hrfv-mqp8-q5rw"},{"url":"https://github.com/pallets/werkzeug/commit/b1916c0c083e0be1c9d887ee2f3d696922bfc5c1"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-46136"},{"url":"https://github.com/pallets/werkzeug/commit/f3c803b3ade485a45f12b6d6617595350c0f03e2"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/werkzeug/PYSEC-2023-221.yaml"},{"url":"https://github.com/pallets/werkzeug/commit/f2300208d5e2a5076cbbb4c2aad71096fd040ef9"},{"url":"https://security.netapp.com/advisory/ntap-20231124-0008/"},{"url":"https://github.com/advisories/GHSA-hrfv-mqp8-q5rw"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:02Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"idna"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jjg7-2v4v-x38h"},{"type":"CVE","value":"CVE-2024-3651"}],"references":[{"url":"https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-3651"},{"url":"https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d"},{"url":"https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/idna/PYSEC-2024-60.yaml"},{"url":"https://github.com/advisories/GHSA-jjg7-2v4v-x38h"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:02Z","securityVulnerability":{"severity":"HIGH","package":{"name":"sqlparse"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-2m57-hf25-phgg"},{"type":"CVE","value":"CVE-2024-4340"}],"references":[{"url":"https://github.com/andialbrecht/sqlparse/security/advisories/GHSA-2m57-hf25-phgg"},{"url":"https://github.com/andialbrecht/sqlparse/commit/b4a39d9850969b4e1d6940d32094ee0b42a2cf03"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-4340"},{"url":"https://research.jfrog.com/vulnerabilities/sqlparse-stack-exhaustion-dos-jfsa-2024-001031292"},{"url":"https://github.com/advisories/GHSA-2m57-hf25-phgg"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:02Z","securityVulnerability":{"severity":"HIGH","package":{"name":"gunicorn"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w3h3-4rj7-4ph4"},{"type":"CVE","value":"CVE-2024-1135"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-1135"},{"url":"https://huntr.com/bounties/22158e34-cfd5-41ad-97e0-a780773d96c1"},{"url":"https://github.com/benoitc/gunicorn/commit/ac29c9b0a758d21f1e0fb3b3457239e523fa9f1d"},{"url":"https://github.com/benoitc/gunicorn/releases/tag/22.0.0"},{"url":"https://lists.debian.org/debian-lts-announce/2024/06/msg00027.html"},{"url":"https://github.com/advisories/GHSA-w3h3-4rj7-4ph4"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:03Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Jinja2"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-h75v-3vvj-5mfj"},{"type":"CVE","value":"CVE-2024-34064"}],"references":[{"url":"https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj"},{"url":"https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-34064"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/567XIGSZMABG6TSMYWD7MIYNJSUQQRUC"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GCLF44KY43BSVMTE6S53B4V5WP3FRRSE"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SSCBHIL6BYKR5NRCBXP4XMP2CEEKGFVS"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZALNWE3TXPPHVPSI3AZ5CTMSTAVN5UMS"},{"url":"https://github.com/advisories/GHSA-h75v-3vvj-5mfj"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:03Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Werkzeug"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-2g68-c3qc-8985"},{"type":"CVE","value":"CVE-2024-34069"}],"references":[{"url":"https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985"},{"url":"https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-34069"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ"},{"url":"https://security.netapp.com/advisory/ntap-20240614-0004"},{"url":"https://github.com/advisories/GHSA-2g68-c3qc-8985"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:03Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"requests"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9wx4-h78v-vm56"},{"type":"CVE","value":"CVE-2024-35195"}],"references":[{"url":"https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"},{"url":"https://github.com/psf/requests/pull/6655"},{"url":"https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-35195"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"},{"url":"https://github.com/advisories/GHSA-9wx4-h78v-vm56"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:03Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"urllib3"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-34jh-p97f-mpxf"},{"type":"CVE","value":"CVE-2024-37891"}],"references":[{"url":"https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891"},{"url":"https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468"},{"url":"https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e"},{"url":"https://github.com/advisories/GHSA-34jh-p97f-mpxf"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:03Z","securityVulnerability":{"severity":"LOW","package":{"name":"certifi"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-248v-346w-9cwc"},{"type":"CVE","value":"CVE-2024-39689"}],"references":[{"url":"https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc"},{"url":"https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39689"},{"url":"https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI"},{"url":"https://github.com/advisories/GHSA-248v-346w-9cwc"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:03Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qg2p-9jwr-mmqf"},{"type":"CVE","value":"CVE-2024-38875"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-38875"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/7285644640f085f41d60ab0c8ae4e9153f0485db"},{"url":"https://github.com/django/django/commit/79f368764295df109a37192f6182fb6f361d85b5"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-56.yaml"},{"url":"https://github.com/advisories/GHSA-qg2p-9jwr-mmqf"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:04Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9jmf-237g-qf46"},{"type":"CVE","value":"CVE-2024-39330"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39330"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/2b00edc0151a660d1eb86da4059904a0fc4e095e"},{"url":"https://github.com/django/django/commit/9f4f63e9ebb7bf6cb9547ee4e2526b9b96703270"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-58.yaml"},{"url":"https://github.com/advisories/GHSA-9jmf-237g-qf46"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:04Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-x7q2-wr7g-xqmf"},{"type":"CVE","value":"CVE-2024-39329"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39329"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/07cefdee4a9d1fcd9a3a631cbd07c78defd1923b"},{"url":"https://github.com/django/django/commit/156d3186c96e3ec2ca73b8b25dc2ef366e38df14"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-57.yaml"},{"url":"https://github.com/advisories/GHSA-x7q2-wr7g-xqmf"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:04Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-f6f8-9mx6-9mx2"},{"type":"CVE","value":"CVE-2024-39614"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39614"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3"},{"url":"https://github.com/django/django/commit/8e7a44e4bec0f11474699c3111a5e0a45afe7f49"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-59.yaml"},{"url":"https://github.com/advisories/GHSA-f6f8-9mx6-9mx2"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:04Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"apache-airflow"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-j482-47xf-p25c"},{"type":"CVE","value":"CVE-2024-39863"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39863"},{"url":"https://github.com/apache/airflow/pull/40475"},{"url":"https://lists.apache.org/thread/gxkvs279f1mbvckv5q65worr6how20o3"},{"url":"https://github.com/apache/airflow/commit/f18f48492dc69f392e45567580b6ddb0c070ea58"},{"url":"https://github.com/advisories/GHSA-j482-47xf-p25c"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:04Z","securityVulnerability":{"severity":"HIGH","package":{"name":"apache-airflow"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-g5hv-r743-v8pm"},{"type":"CVE","value":"CVE-2024-39877"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39877"},{"url":"https://github.com/apache/airflow/pull/40522"},{"url":"https://lists.apache.org/thread/1xhj9dkp37d6pzn24ll2mf94wbqnb2y1"},{"url":"https://github.com/apache/airflow/commit/8159f6e24704f5e0e3b3217cf79ecf5083dce531"},{"url":"https://github.com/advisories/GHSA-g5hv-r743-v8pm"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:04Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"apache-airflow-providers-fab"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-62qf-qm3g-fvcw"},{"type":"CVE","value":"CVE-2024-42447"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-42447"},{"url":"https://github.com/apache/airflow/pull/40784"},{"url":"https://lists.apache.org/thread/2zoo8cjlwfjhbfdxfgltcm0hnc0qmc52"},{"url":"https://github.com/advisories/GHSA-62qf-qm3g-fvcw"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:04Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jh75-99hh-qvx9"},{"type":"CVE","value":"CVE-2024-41989"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41989"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/27900fe56f3d3cabb4aeb6ccb82f92bab29073a8"},{"url":"https://github.com/django/django/commit/fc76660f589ac07e45e9cd34ccb8087aeb11904b"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-67.yaml"},{"url":"https://github.com/advisories/GHSA-jh75-99hh-qvx9"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:05Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-795c-9xpc-xw6g"},{"type":"CVE","value":"CVE-2024-41990"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41990"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/7b7b909579c8311c140c89b8a9431bf537febf93"},{"url":"https://github.com/django/django/commit/d0a82e26a74940bf0c78204933c3bdd6a283eb88"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-68.yaml"},{"url":"https://github.com/advisories/GHSA-795c-9xpc-xw6g"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:05Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-pv4p-cwwg-4rph"},{"type":"CVE","value":"CVE-2024-42005"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-42005"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/32ebcbf2e1fe3e5ba79a6554a167efce81f7422d"},{"url":"https://github.com/django/django/commit/f4af67b9b41e0f4c117a8741da3abbd1c869ab28"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-70.yaml"},{"url":"https://github.com/advisories/GHSA-pv4p-cwwg-4rph"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:05Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-r836-hh6v-rg5g"},{"type":"CVE","value":"CVE-2024-41991"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41991"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/523da8771bce321023f490f70d71a9e973ddc927"},{"url":"https://github.com/django/django/commit/efea1ef7e2190e3f77ca0651b5458297bc0f6a9f"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-69.yaml"},{"url":"https://github.com/advisories/GHSA-r836-hh6v-rg5g"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:05Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"aiohttp"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jwhx-xcg6-8xhj"},{"type":"CVE","value":"CVE-2024-42367"}],"references":[{"url":"https://github.com/aio-libs/aiohttp/security/advisories/GHSA-jwhx-xcg6-8xhj"},{"url":"https://github.com/aio-libs/aiohttp/pull/8653"},{"url":"https://github.com/aio-libs/aiohttp/commit/ce2e9758814527589b10759a20783fb03b98339f"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-42367"},{"url":"https://github.com/aio-libs/aiohttp/blob/e0ff5246e1d29b7710ab1a2bbc972b48169f1c05/aiohttp/web_fileresponse.py#L177"},{"url":"https://github.com/aio-libs/aiohttp/blob/e0ff5246e1d29b7710ab1a2bbc972b48169f1c05/aiohttp/web_urldispatcher.py#L674"},{"url":"https://github.com/advisories/GHSA-jwhx-xcg6-8xhj"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:05Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"apache-airflow"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w7cp-g8v7-r54m"},{"type":"CVE","value":"CVE-2024-41937"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41937"},{"url":"https://github.com/apache/airflow/pull/40933"},{"url":"https://lists.apache.org/thread/lwlmgg6hqfmkpvw5py4w53hxyl37jl6d"},{"url":"https://github.com/apache/airflow/commit/f1852c2ab28b155e196569780013fbb61a4a1f98"},{"url":"https://github.com/advisories/GHSA-w7cp-g8v7-r54m"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:05Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"axios"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-wf5p-g6vw-rhxx"},{"type":"CVE","value":"CVE-2023-45857"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-45857"},{"url":"https://github.com/axios/axios/issues/6006"},{"url":"https://github.com/axios/axios/issues/6022"},{"url":"https://github.com/axios/axios/pull/6028"},{"url":"https://github.com/axios/axios/commit/96ee232bd3ee4de2e657333d4d2191cd389e14d0"},{"url":"https://github.com/axios/axios/releases/tag/v1.6.0"},{"url":"https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459"},{"url":"https://github.com/axios/axios/pull/6091"},{"url":"https://github.com/axios/axios/commit/2755df562b9c194fba6d8b609a383443f6a6e967"},{"url":"https://github.com/axios/axios/releases/tag/v0.28.0"},{"url":"https://security.netapp.com/advisory/ntap-20240621-0006"},{"url":"https://github.com/advisories/GHSA-wf5p-g6vw-rhxx"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:06Z","securityVulnerability":{"severity":"HIGH","package":{"name":"orjson"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-pwr2-4v36-6qpr"},{"type":"CVE","value":"CVE-2024-27454"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-27454"},{"url":"https://github.com/ijl/orjson/issues/458"},{"url":"https://github.com/ijl/orjson/commit/b0e4d2c06ce06c6e63981bf0276e4b7c74e5845e"},{"url":"https://github.com/ijl/orjson/blob/master/CHANGELOG.md#3915"},{"url":"https://monicz.dev/CVE-2024-27454"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/orjson/PYSEC-2024-40.yaml"},{"url":"https://github.com/advisories/GHSA-pwr2-4v36-6qpr"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:06Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"pillow"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-44wm-f244-xhp3"},{"type":"CVE","value":"CVE-2024-28219"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-28219"},{"url":"https://pillow.readthedocs.io/en/stable/releasenotes/10.3.0.html#security"},{"url":"https://github.com/python-pillow/Pillow/commit/2a93aba5cfcf6e241ab4f9392c13e3b74032c061"},{"url":"https://lists.debian.org/debian-lts-announce/2024/04/msg00008.html"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4XLPUT3VK4GQ6EVY525TT2QNUIXNRU5M"},{"url":"https://github.com/advisories/GHSA-44wm-f244-xhp3"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:06Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"idna"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jjg7-2v4v-x38h"},{"type":"CVE","value":"CVE-2024-3651"}],"references":[{"url":"https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-3651"},{"url":"https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d"},{"url":"https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/idna/PYSEC-2024-60.yaml"},{"url":"https://github.com/advisories/GHSA-jjg7-2v4v-x38h"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:06Z","securityVulnerability":{"severity":"HIGH","package":{"name":"sqlparse"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-2m57-hf25-phgg"},{"type":"CVE","value":"CVE-2024-4340"}],"references":[{"url":"https://github.com/andialbrecht/sqlparse/security/advisories/GHSA-2m57-hf25-phgg"},{"url":"https://github.com/andialbrecht/sqlparse/commit/b4a39d9850969b4e1d6940d32094ee0b42a2cf03"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-4340"},{"url":"https://research.jfrog.com/vulnerabilities/sqlparse-stack-exhaustion-dos-jfsa-2024-001031292"},{"url":"https://github.com/advisories/GHSA-2m57-hf25-phgg"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:06Z","securityVulnerability":{"severity":"HIGH","package":{"name":"gunicorn"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w3h3-4rj7-4ph4"},{"type":"CVE","value":"CVE-2024-1135"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-1135"},{"url":"https://huntr.com/bounties/22158e34-cfd5-41ad-97e0-a780773d96c1"},{"url":"https://github.com/benoitc/gunicorn/commit/ac29c9b0a758d21f1e0fb3b3457239e523fa9f1d"},{"url":"https://github.com/benoitc/gunicorn/releases/tag/22.0.0"},{"url":"https://lists.debian.org/debian-lts-announce/2024/06/msg00027.html"},{"url":"https://github.com/advisories/GHSA-w3h3-4rj7-4ph4"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:06Z","securityVulnerability":{"severity":"LOW","package":{"name":"tqdm"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-g7vv-2v7x-gj9p"},{"type":"CVE","value":"CVE-2024-34062"}],"references":[{"url":"https://github.com/tqdm/tqdm/security/advisories/GHSA-g7vv-2v7x-gj9p"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-34062"},{"url":"https://github.com/tqdm/tqdm/commit/4e613f84ed2ae029559f539464df83fa91feb316"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PA3GIGHPWAHCTT4UF57LTPZGWHAX3GW6"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QRECVQCCESHBS3UJOWNXQUIX725TKNY6"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VA337CYUS4SLRFV2P6MX6MZ2LKFURKJC"},{"url":"https://github.com/advisories/GHSA-g7vv-2v7x-gj9p"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:06Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Jinja2"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-h75v-3vvj-5mfj"},{"type":"CVE","value":"CVE-2024-34064"}],"references":[{"url":"https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj"},{"url":"https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-34064"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/567XIGSZMABG6TSMYWD7MIYNJSUQQRUC"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GCLF44KY43BSVMTE6S53B4V5WP3FRRSE"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SSCBHIL6BYKR5NRCBXP4XMP2CEEKGFVS"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZALNWE3TXPPHVPSI3AZ5CTMSTAVN5UMS"},{"url":"https://github.com/advisories/GHSA-h75v-3vvj-5mfj"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:07Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"requests"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9wx4-h78v-vm56"},{"type":"CVE","value":"CVE-2024-35195"}],"references":[{"url":"https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"},{"url":"https://github.com/psf/requests/pull/6655"},{"url":"https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-35195"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"},{"url":"https://github.com/advisories/GHSA-9wx4-h78v-vm56"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:07Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"urllib3"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-34jh-p97f-mpxf"},{"type":"CVE","value":"CVE-2024-37891"}],"references":[{"url":"https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891"},{"url":"https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468"},{"url":"https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e"},{"url":"https://github.com/advisories/GHSA-34jh-p97f-mpxf"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:07Z","securityVulnerability":{"severity":"LOW","package":{"name":"certifi"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-248v-346w-9cwc"},{"type":"CVE","value":"CVE-2024-39689"}],"references":[{"url":"https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc"},{"url":"https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39689"},{"url":"https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI"},{"url":"https://github.com/advisories/GHSA-248v-346w-9cwc"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:07Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qg2p-9jwr-mmqf"},{"type":"CVE","value":"CVE-2024-38875"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-38875"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/7285644640f085f41d60ab0c8ae4e9153f0485db"},{"url":"https://github.com/django/django/commit/79f368764295df109a37192f6182fb6f361d85b5"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-56.yaml"},{"url":"https://github.com/advisories/GHSA-qg2p-9jwr-mmqf"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:07Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9jmf-237g-qf46"},{"type":"CVE","value":"CVE-2024-39330"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39330"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/2b00edc0151a660d1eb86da4059904a0fc4e095e"},{"url":"https://github.com/django/django/commit/9f4f63e9ebb7bf6cb9547ee4e2526b9b96703270"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-58.yaml"},{"url":"https://github.com/advisories/GHSA-9jmf-237g-qf46"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:07Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-x7q2-wr7g-xqmf"},{"type":"CVE","value":"CVE-2024-39329"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39329"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/07cefdee4a9d1fcd9a3a631cbd07c78defd1923b"},{"url":"https://github.com/django/django/commit/156d3186c96e3ec2ca73b8b25dc2ef366e38df14"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-57.yaml"},{"url":"https://github.com/advisories/GHSA-x7q2-wr7g-xqmf"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:07Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-f6f8-9mx6-9mx2"},{"type":"CVE","value":"CVE-2024-39614"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39614"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3"},{"url":"https://github.com/django/django/commit/8e7a44e4bec0f11474699c3111a5e0a45afe7f49"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-59.yaml"},{"url":"https://github.com/advisories/GHSA-f6f8-9mx6-9mx2"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:08Z","securityVulnerability":{"severity":"LOW","package":{"name":"sentry-sdk"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-g92j-qhmh-64v2"},{"type":"CVE","value":"CVE-2024-40647"}],"references":[{"url":"https://github.com/getsentry/sentry-python/security/advisories/GHSA-g92j-qhmh-64v2"},{"url":"https://github.com/getsentry/sentry-python/pull/3251"},{"url":"https://github.com/getsentry/sentry-python/commit/763e40aa4cb57ecced467f48f78f335c87e9bdff"},{"url":"https://docs.python.org/3/library/subprocess.html"},{"url":"https://docs.sentry.io/platforms/python/integrations/default-integrations"},{"url":"https://docs.sentry.io/platforms/python/integrations/default-integrations/#stdlib"},{"url":"https://github.com/getsentry/sentry-python/releases/tag/2.8.0"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-40647"},{"url":"https://github.com/advisories/GHSA-g92j-qhmh-64v2"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:08Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jh75-99hh-qvx9"},{"type":"CVE","value":"CVE-2024-41989"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41989"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/27900fe56f3d3cabb4aeb6ccb82f92bab29073a8"},{"url":"https://github.com/django/django/commit/fc76660f589ac07e45e9cd34ccb8087aeb11904b"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-67.yaml"},{"url":"https://github.com/advisories/GHSA-jh75-99hh-qvx9"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:08Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-795c-9xpc-xw6g"},{"type":"CVE","value":"CVE-2024-41990"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41990"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/7b7b909579c8311c140c89b8a9431bf537febf93"},{"url":"https://github.com/django/django/commit/d0a82e26a74940bf0c78204933c3bdd6a283eb88"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-68.yaml"},{"url":"https://github.com/advisories/GHSA-795c-9xpc-xw6g"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:08Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-pv4p-cwwg-4rph"},{"type":"CVE","value":"CVE-2024-42005"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-42005"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/32ebcbf2e1fe3e5ba79a6554a167efce81f7422d"},{"url":"https://github.com/django/django/commit/f4af67b9b41e0f4c117a8741da3abbd1c869ab28"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-70.yaml"},{"url":"https://github.com/advisories/GHSA-pv4p-cwwg-4rph"}]}}},{"dismissedAt":null,"createdAt":"2024-08-22T13:09:08Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-r836-hh6v-rg5g"},{"type":"CVE","value":"CVE-2024-41991"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41991"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/523da8771bce321023f490f70d71a9e973ddc927"},{"url":"https://github.com/django/django/commit/efea1ef7e2190e3f77ca0651b5458297bc0f6a9f"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-69.yaml"},{"url":"https://github.com/advisories/GHSA-r836-hh6v-rg5g"}]}}}]},"grade":"E"}]}